export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const SET_PRODUCT_ITEM = "SET_PRODUCT_ITEM";

export const SET_OBJECT_PAIR = "SET_OBJECT_PAIR";
export const SET_COCKTAIL_INGREDIENTS = "SET_COCKTAIL_INGREDIENTS";

export const REMOVE_COCKTAIL_INGREDIENTS = "REMOVE_COCKTAIL_INGREDIENT";

export const ADD_PRODUCT_BEGIN = "ADD_PRODUCT_BEGIN";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const GET_ALL_PRODUCTS_BEGIN = "GET_ALL_PRODUCTS_BEGIN";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

export const SET_SHOW_CARDS = "SET_SHOW_CARDS";
export const SET_IS_EDITING = "SET_IS_EDITING";

export const EDIT_PRODUCT_BEGIN = "EDIT_PRODUCT_BEGIN";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

export const GET_INVENTORIES_BEGIN = "GET_INVENTORIES_BEGIN";
export const GET_INVENTORIES_SUCCESS = "GET_INVENTORIES_SUCCESS";
export const GET_INVENTORIES_ERROR = "GET_INVENTORIES_ERROR";

export const UPDATE_INVENTORIES_BEGIN = "UPDATE_INVENTORIES_BEGIN";
export const UPDATE_INVENTORIES_SUCCESS = "UPDATE_INVENTORIES_SUCCESS";
export const UPDATE_INVENTORIES_ERROR = "UPDATE_INVENTORIES_ERROR";

export const SET_INVENTORY_PAIR = "SET_INVENTORY_PAIR";

export const UPDATE_PRODUCT_FROM_INVENTORY = "UPDATE_PRODUCT_FROM_INVENTORY";
