export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const SET_PRODUCT_ITEM = "SET_PRODUCT_ITEM";

export const SET_OBJECT_PAIR = "SET_OBJECT_PAIR";
export const SET_COCKTAIL_INGREDIENTS = "SET_COCKTAIL_INGREDIENTS";

export const REMOVE_COCKTAIL_INGREDIENTS = "REMOVE_COCKTAIL_INGREDIENT";

export const ADD_PRODUCT_BEGIN = "ADD_PRODUCT_BEGIN";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const SET_SHOW_CARDS = "SET_SHOW_CARDS";
